### ISSUE TITLE
ESRI logo trademark

### ISSUE THREAD

**Issue by saberraz** [havochvatten/ImageServerConnector-QGIS-Plugin#4]
ESRI globe logo is covered by their trademark:
https://www.esri.com/en-us/legal/copyright-trademarks

Best to either avoid using their logo altogether or ensure it does not breach it.

**Comment by antmyrhav** [comment]
Thank you for your feedback. The logotype and texts are now updated to properly convey our status. Also added a disclaimer stating that we are not affiliated with Esri. Once again, thank you.
