### ISSUE TITLE
QGIS bug report #20536 was fixed

### ISSUE THREAD

**Issue by adrianocunha3000** [havochvatten/ImageServerConnector-QGIS-Plugin#6]
Hello!

QGIS bug report #20536 "Redrawing raster layer after file changed in QGIS?" was fixed/implemented.

Regards,

Adriano Cunha

**Comment by adrianocunha3000** [comment]
P.S.: Kudos to you for this plugin!

**Comment by antmyrhav** [comment]
Yes, we have updated the plugin to make use of this. Thank you.

**Comment by adrianocunha3000** [comment]
Hello!

What is the relation between this fix and the Readme.md update warning, please?

Regards,

Adriano Cunha

**Comment by adrianocunha3000** [comment]
Hello!


What is the relation between this fix and the readme file warning, please? Shouldn't the readme file be updated?


Regards,

Adriano Cunha

**Comment by antmyrhav** [comment]
I forgot to update the readme, I have done that now, thank you.
